[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@uniswap/v2-core/=lib/v2-core/", "@uniswap/v2-periphery/=lib/v2-periphery/"]
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
